default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade --py37-plus
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [python]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black --config pyproject.toml
        types: [python]
        language: system

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
      - id: mypy
        args: [--install-types, --non-interactive]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args: ['--convention=google']
